# Generated by Django 5.2.11 on 2026-02-08 10:16

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('importance', models.SmallIntegerField(default=3)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('start_date', models.DateField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='DONE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='habits.habit')),
            ],
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='habits.habit')),
            ],
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user'], name='habits_habi_user_id_599ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'archived_at'], name='habits_habi_user_id_b6c5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'start_date'], name='habits_habi_user_id_173195_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_e5e773_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['date'], name='habits_habi_date_9de476_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitcheckin',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='uniq_habit_date'),
        ),
    ]
